# Generated by Django 4.2.5 on 2025-04-08 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_train', '0006_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='tags',
        ),
        migrations.AddField(
            model_name='entry',
            name='tags',
            field=models.ManyToManyField(related_name='entries', to='db_train.tag'),
        ),
    ]
